### ISSUE TITLE
No Depth Camera and Limited IR Camera Streaming

### ISSUE THREAD

**Issue by danielleamya** [prisonerjohn/ofxAzureKinect#9]
Hi,

I am having an issue with getting the depth camera to work in the stream example. I have not edited the original code in any way. Upon running the example, I can clearly see the RGB camera capture clearly. However I can barely see the IR camera feed (does not appear the same way it does in the Azure Kinect Viewer application, and cannot see the depth camera at all.

To reproduce, navigate to the example-streams folder, and run the example-streams VS solution. Expected is that the live feed would look identical to the live feed from the Azure Kinect Viewer application, but this is not the case.

OF vs Azure Kinect Viewer:
<img width="1451" alt="Screenshot 2020-01-29 11 38 35" src="https://user-images.githubusercontent.com/14864541/73384497-5f07d600-4299-11ea-930b-4101364e70ef.png">
<img width="1451" alt="Screenshot 2020-01-29 11 39 00" src="https://user-images.githubusercontent.com/14864541/73384501-616a3000-4299-11ea-972b-21636910bb45.png">

Running:
Windows 10, of_v0.11.0, Visual Studio 2019

**Comment by digitalcoleman** [comment]
I can confirm this issue. Running Windows 10, OF 0.11.0, and VS 2017

**Comment by digitalcoleman** [comment]
Ok, I spent a lot of time on this and realized it is a 16bit color issue. Basically, the IR and Depth images are captured and stored in ofShortPixels for 16bit greyscale. But then they are drawn to 8-bit monitors and essentially show nothing. Would need to add a conversion to get them to show up, and from what I see, that requires a lookup table and likely a shader to do it efficiently? (Way beyond my skill). That is to say that the example is "working," it just is not currently useful.

**Comment by aaronsherwood** [comment]
Any update on this? I'm also having the same problem. I just need the depth image.

**Comment by prisonerjohn** [comment]
Hello, and sorry for the ridiculous delay on this. Like @digitalcoleman said, it looks to me like everything is working fine. You just can't see the depth image very well because I'm sending the raw depth which has a huge range, and whatever is near the camera is very close to black.
I just added an example called `example-scaled-depth` that shows how you can remap the depth data into a range that is easier to see. I hope this helps!
![image](https://github.com/prisonerjohn/ofxAzureKinect/assets/119702/7889b42b-83e4-45a2-8eb3-e2625c35bbe8)
